AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/tasks/cucumber.rake'
    - Guardfile
    - Gemfile
    - 'hooks/**/*'

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Enabled: true

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 26
